In [12]:
# Import all required libraries
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import matplotlib.pyplot as plt
import seaborn as sns
from numpy import vectorize

In [5]:
df=pd.read_csv('/content/UpdatedResumeDataSet.csv',encoding='utf-8')
print('Shape of data frame',df.shape)
df.head(10)

Shape of data frame (962, 2)

       Category                                             Resume
0  Data Science  Skills * Programming Languages: Python (pandas...
1  Data Science  Education Details \r\nMay 2013 to May 2017 B.E...
2  Data Science  Areas of Interest Deep Learning, Control Syste...
3  Data Science  Skills â¢ R â¢ Python â¢ SAP HANA â¢ Table...
4  Data Science  Education Details \r\n MCA   YMCAUST,  Faridab...
5  Data Science  SKILLS C Basics, IOT, Python, MATLAB, Data Sci...
6  Data Science  Skills â¢ Python â¢ Tableau â¢ Data Visuali...
7  Data Science  Education Details \r\n B.Tech   Rayat and Bahr...
8  Data Science  Personal Skills â¢ Ability to quickly grasp t...
9  Data Science  Expertise â Data and Quantitative Analysis â...

In [6]:
print('\n Columns',df.columns.tolist())

 Columns ['Category', 'Resume']

In [10]:
sample_df=df.sample(10,random_state=42).reset_index(drop=True)
sample_df

                    Category                                             Resume
0             Java Developer  TECHNICAL SKILLS Programming Languages: Java (...
1             Java Developer  TECHNICALSKILLS SpringMVC, Hibernate, JDBC, Ja...
2             Java Developer  Education Details \r\nJanuary 2013 Master of E...
3                     Hadoop  Skill Set: Hadoop, Map Reduce, HDFS, Hive, Sqo...
4         Health and fitness  Education Details \r\nJanuary 1992 to January ...
5  Network Security Engineer  Technical Expertise: â¢ Cisco ASA, Checkpoint...
6        Mechanical Engineer  Education Details \r\nMay 1999 to September 20...
7         Automation Testing  Technical Skills Summary I have completed "COR...
8                   Advocate  Education Details \r\n LLB.   Dibrugarh Univer...
9         Health and fitness  SKILLS: Computer: â¢ Can easily operate in Op...

In [17]:
sample_df=sample_df.rename(columns={'Resume':'Resume_Text'})
sample_df
print(sample_df.shape)

(10, 2)

In [20]:
vectorizer=TfidfVectorizer(stop_words='english')
tfidf_matrix=vectorizer.fit_transform(sample_df['Resume_Text'])
tfidf_matrix.shape

(10, 1125)

In [25]:
similartiness_matrix=cosine_similarity(tfidf_matrix)
sim_df=pd.DataFrame(similartiness_matrix,index=sample_df['Category']+'_'+sample_df.index.astype(str),
                    columns=sample_df['Category']+'_'+sample_df.index.astype(str))

sim_df.round(2).head(3)

                  Java Developer_0  ...  Health and fitness_9
Java Developer_0              1.00  ...                  0.08
Java Developer_1              0.41  ...                  0.06
Java Developer_2              0.24  ...                  0.03

[3 rows x 10 columns]

**Resume Screen Example 2**

In [26]:
resumes={
    'candidates':['Sam','Amit','Maan'],
    'resume_text':['Python Developer Skill in Django,Flask,Rest API and MySQL',
                   'Machine Learning engineer experience in Python,TenseFlow,NLP and data analysis',
                   'Full stack developer with .net, javascript,React,Noda.js and MongoDB experience']
}

In [38]:
df=pd.DataFrame(resumes)
df

  candidates                                        resume_text
0        Sam  Python Developer Skill in Django,Flask,Rest AP...
1       Amit  Machine Learning engineer experience in Python...
2       Maan  Full stack developer with .net, javascript,Rea...

In [42]:
# Tambah candidate lagi
df.loc[len(df)]=['Sav','Backend developer skilled in Python, Flask and SQL']

In [40]:
vectorize=TfidfVectorizer(stop_words='english')
tfidf_matrix=vectorizer.fit_transform(df['resume_text'])
tfidf_matrix.shape
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 32 stored elements and shape (4, 26)>

In [41]:
similartiness_matrix=cosine_similarity(tfidf_matrix)
sim_df=pd.DataFrame(similartiness_matrix,index=df['candidates'],columns=df['candidates'])
sim_df.round(2)

candidates   Sam  Amit  Maan   Sav
candidates
Sam         1.00  0.06  0.06  0.27
Amit        0.06  1.00  0.08  0.07
Maan        0.06  0.08  1.00  0.07
Sav         0.27  0.07  0.07  1.00