# BASIC PANDAS EXAMPLE TO READ OUT FROM AN EXCEL FILE

In [1]:
import pandas as pd

In [2]:
df=pd.read_excel("students.xlsx")

In [4]:
print('Printing Data Frame as follows')
df

Printing Data Frame as follows

    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90
5  Rohit   23     45

In [8]:
dfpatients = pd.read_csv(r'C:\Users\User\OneDrive\Desktop\AIML\DAY - 10\patients.csv')

In [12]:
dfpatients['name']

0      Richard Rodriguez
1         Shannon Walker
2           Julia Torres
3        Crystal Johnson
4            Garrett Lin
             ...
995           Amber Vang
996         Martha Smith
997       Jennifer James
998       Kara Hernandez
999      Lorraine Turner
Name: name, Length: 1000, dtype: object

In [13]:
print(dfpatients['name'])

0      Richard Rodriguez
1         Shannon Walker
2           Julia Torres
3        Crystal Johnson
4            Garrett Lin
             ...
995           Amber Vang
996         Martha Smith
997       Jennifer James
998       Kara Hernandez
999      Lorraine Turner
Name: name, Length: 1000, dtype: object

## Head in dataframe ....head maksud first ..contoh (5)...ni first 5 dia akan amek

In [14]:
dfpatients.head()

,patient_id,name,age,arrival_date,departure_date,service,satisfaction
0,PAT-09484753,Richard Rodriguez,24,2025-03-16,2025-03-22,surgery,61
1,PAT-f0644084,Shannon Walker,6,2025-12-13,2025-12-14,surgery,83
2,PAT-ac6162e4,Julia Torres,24,2025-06-29,2025-07-05,general_medicine,83
3,PAT-3dda2bb5,Crystal Johnson,32,2025-10-12,2025-10-23,emergency,81
4,PAT-08591375,Garrett Lin,25,2025-02-18,2025-02-25,ICU,76

In [15]:
dfpatients.head(2)

,patient_id,name,age,arrival_date,departure_date,service,satisfaction
0,PAT-09484753,Richard Rodriguez,24,2025-03-16,2025-03-22,surgery,61
1,PAT-f0644084,Shannon Walker,6,2025-12-13,2025-12-14,surgery,83

# Tail example (for students)..tail maksud last ..contoh (5)...ni last 5 dia akan amek

In [16]:
print('Last two students in excel sheet')
df.tail(2)

Last two students in excel sheet

    Name  Age  Marks
4    Sam   25     90
5  Rohit   23     45

In [18]:
dfpatients.tail(5)

,patient_id,name,age,arrival_date,departure_date,service,satisfaction
995,PAT-a01bf534,Amber Vang,26,2025-12-02,2025-12-04,emergency,91
996,PAT-87fa07bd,Martha Smith,89,2025-11-18,2025-11-30,emergency,99
997,PAT-8f07e894,Jennifer James,72,2025-12-12,2025-12-21,ICU,69
998,PAT-4ae301e1,Kara Hernandez,47,2025-02-08,2025-02-20,ICU,61
999,PAT-e2ef9c5f,Lorraine Turner,64,2025-05-04,2025-05-08,general_medicine,83

## Shape example that returns to you (rows, columns)

In [19]:
dfpatients.shape

(1000, 7)

In [20]:
df.shape

(6, 3)

In [22]:
rows,cols=dfpatients.shape
print(f"Rows: {rows} Columns: {cols} ")

Rows: 1000 Columns: 7

In [23]:
rows,cols=df.shape
print("Rows and Colums in student sheet")
print(f"Rows: {rows} Columns: {cols} ")

Rows and Colums in student sheet
Rows: 6 Columns: 3

# Values: in dataframe

In [24]:
print("Student Value")
df.values

Student Value

array([['John', 20, 85],
       ['Alice', 22, 90],
       ['Bob', 21, 78],
       ['Sara', 23, 92],
       ['Sam', 25, 90],
       ['Rohit', 23, 45]], dtype=object)

In [27]:
print("Patients Value")
dfpatients.values

Patients Value

array([['PAT-09484753', 'Richard Rodriguez', 24, ..., '2025-03-22',
        'surgery', 61],
       ['PAT-f0644084', 'Shannon Walker', 6, ..., '2025-12-14',
        'surgery', 83],
       ['PAT-ac6162e4', 'Julia Torres', 24, ..., '2025-07-05',
        'general_medicine', 83],
       ...,
       ['PAT-8f07e894', 'Jennifer James', 72, ..., '2025-12-21', 'ICU',
        69],
       ['PAT-4ae301e1', 'Kara Hernandez', 47, ..., '2025-02-20', 'ICU',
        61],
       ['PAT-e2ef9c5f', 'Lorraine Turner', 64, ..., '2025-05-08',
        'general_medicine', 83]], dtype=object)