In [3]:
import pandas as pd

In [7]:
data={'Students':['Amit','Anam','Chi','Sam','Ravi','Jai'],
 'Marks':[85,None,65,75,None,55]}

In [11]:
df=pd.DataFrame(data)
print('Original Data')
df

Original Data

  Students  Marks
0     Amit   85.0
1     Anam    NaN
2      Chi   65.0
3      Sam   75.0
4     Ravi    NaN
5      Jai   55.0

In [12]:
print('Missing Data')
print('Number of Missing values are:',df.isnull().sum())

Missing Data
Number of Missing values are: Students    0
Marks       2
dtype: int64

In [14]:
average_marks=df['Marks'].mean()
print(average_marks)

70.0

In [16]:
df.fillna(average_marks, inplace=True)

In [17]:
print('after fillna() call')
df

after fillna() call

  Students  Marks
0     Amit   85.0
1     Anam   70.0
2      Chi   65.0
3      Sam   75.0
4     Ravi   70.0
5      Jai   55.0

# Let us see it , how we will use in our project

In [26]:
#fillna() example
students_data={'Name':['Amit','Anam','Chi','Sam','Ravi','Jai'], 'Marks':[85,None,65,75,None,55]}
df=pd.DataFrame(students_data)
df

   Name  Marks
0  Amit   85.0
1  Anam    NaN
2   Chi   65.0
3   Sam   75.0
4  Ravi    NaN
5   Jai   55.0

In [27]:
df.fillna(df['Marks'].mean(), inplace=True)

In [28]:
df

   Name  Marks
0  Amit   85.0
1  Anam   70.0
2   Chi   65.0
3   Sam   75.0
4  Ravi   70.0
5   Jai   55.0

# dropna() example

In [30]:
students_data={'Name':['Amit','Anam','Chi','Sam','Ravi','Jai'], 'Marks':[85,None,65,75,None,55]}
df=pd.DataFrame(students_data)
print('Original Data')
df

Original Data

   Name  Marks
0  Amit   85.0
1  Anam    NaN
2   Chi   65.0
3   Sam   75.0
4  Ravi    NaN
5   Jai   55.0

In [31]:
df=df.dropna(subset=['Marks'])

In [32]:
print('Dataset after dropna()')
df

Dataset after dropna()

   Name  Marks
0  Amit   85.0
2   Chi   65.0
3   Sam   75.0
5   Jai   55.0

In [34]:
students_data={'Name':['Amit','Anam','Chi','Sam','Ravi','Jai'], 'Marks':[85,None,65,75,None,55]}
df=pd.DataFrame(students_data)
print('Original Data')
df

Original Data

   Name  Marks
0  Amit   85.0
1  Anam    NaN
2   Chi   65.0
3   Sam   75.0
4  Ravi    NaN
5   Jai   55.0

In [35]:
df=df.dropna()
print('Dataset after dropna()')
df

Dataset after dropna()

   Name  Marks
0  Amit   85.0
2   Chi   65.0
3   Sam   75.0
5   Jai   55.0

In [66]:
emp_data={
    "Name":['Sam','Ali','Chang','Xi','Viz','Suhail'],
    "Age":[35,None,25,20,24,None],
    "Salary":[50000,30000,20000,40000,None,None],
    }
df=pd.DataFrame(emp_data)
print('Original Data')
df

Original Data

     Name   Age   Salary
0     Sam  35.0  50000.0
1     Ali   NaN  30000.0
2   Chang  25.0  20000.0
3      Xi  20.0  40000.0
4     Viz  24.0      NaN
5  Suhail   NaN      NaN

In [67]:
print(df.isnull().sum())

Name      0
Age       2
Salary    2
dtype: int64

In [38]:
df_drop=df.dropna()
df_drop

    Name   Age   Salary
0    Sam  35.0  50000.0
2  Chang  25.0  20000.0
3     Xi  20.0  40000.0

In [39]:
df_drop_salary=df.dropna(subset=['Salary'])
df_drop_salary

    Name   Age   Salary
0    Sam  35.0  50000.0
1    Ali   NaN  30000.0
2  Chang  25.0  20000.0
3     Xi  20.0  40000.0

In [46]:
df

     Name   Age   Salary
0     Sam  35.0  50000.0
1     Ali  26.0  30000.0
2   Chang  25.0  20000.0
3      Xi  20.0  40000.0
4     Viz  24.0     26.0
5  Suhail  26.0     26.0

In [61]:
#fillna example
print(df)

None

In [89]:
emp_data={
    "Name":['Sam','Ali','Chang','Xi','Viz','Suhail'],
    "Age":[35,None,25,20,24,None],
    "Salary":[50000,30000,20000,40000,None,None],
    }
df=pd.DataFrame(emp_data)
print('Original Data')
df

Original Data

     Name   Age   Salary
0     Sam  35.0  50000.0
1     Ali   NaN  30000.0
2   Chang  25.0  20000.0
3      Xi  20.0  40000.0
4     Viz  24.0      NaN
5  Suhail   NaN      NaN

In [90]:
df

     Name   Age   Salary
0     Sam  35.0  50000.0
1     Ali   NaN  30000.0
2   Chang  25.0  20000.0
3      Xi  20.0  40000.0
4     Viz  24.0      NaN
5  Suhail   NaN      NaN

In [91]:
 df.fillna({'Age':df['Age'].mean(),'Salary':df['Salary'].mean()}, inplace=True)

In [92]:
df

     Name   Age   Salary
0     Sam  35.0  50000.0
1     Ali  26.0  30000.0
2   Chang  25.0  20000.0
3      Xi  20.0  40000.0
4     Viz  24.0  35000.0
5  Suhail  26.0  35000.0

In [93]:
emp_data={
    "Name":['Sam','Ali','Chang','Xi','Viz','Suhail'],
    "Age":[35,None,25,20,24,None],
    "Salary":[50000,30000,20000,40000,None,None],
    }
df=pd.DataFrame(emp_data)
df.fillna({'Age':df['Age'].mean(),'Salary':df['Salary'].mean()}, inplace=True)
df

     Name   Age   Salary
0     Sam  35.0  50000.0
1     Ali  26.0  30000.0
2   Chang  25.0  20000.0
3      Xi  20.0  40000.0
4     Viz  24.0  35000.0
5  Suhail  26.0  35000.0

In [5]:
import pandas as pd

In [8]:
df = pd.read_csv('students_performance_dirty.csv')
df.head(5)

print('Number of missing values are:')
print(df.isnull().sum())

Number of missing values are:
gender            8
study_hours       8
attendance_pct    0
math_score        0
reading_score     0
final_score       0
dtype: int64

# Download students_performance_dirty.csv
## find out number of missing data
## drop rows where gender is missing
## fill study_hours with average_hours

In [16]:
# 1. Read dataset
df = pd.read_csv('students_performance_dirty.csv')

In [17]:
# 2. Show first few rows (optional)
print(df.head())

   gender  study_hours  attendance_pct  math_score  reading_score  final_score
0    male          1.7            83.6        62.0           91.0         38.9
1     NaN          2.6            91.2        82.0           60.0         37.5
2  female          2.9            97.5        69.0           57.0         35.0
3  female          4.8            85.7        78.0           62.0         36.5
4    male          3.9           -10.0        64.0           95.0         30.9

In [18]:
# 3. Find number of missing data
print("\nNumber of missing values in each column:")
print(df.isnull().sum())

Number of missing values in each column:
gender            8
study_hours       8
attendance_pct    0
math_score        0
reading_score     0
final_score       0
dtype: int64

In [28]:
# 4. Drop rows where 'gender' is missing
df=df.dropna(subset=['gender'])

In [20]:
# 5. Fill 'study_hours' with the average value
df['study_hours'] = df['study_hours'].fillna(df['study_hours'].mean())

In [21]:
# 6. Verify changes
print("\nAfter cleaning:")
print(df.isnull().sum())

After cleaning:
gender            0
study_hours       0
attendance_pct    0
math_score        0
reading_score     0
final_score       0
dtype: int64

In [29]:
df = pd.read_csv('students_performance_dirty.csv')
print(df.head())

print("\nNumber of missing values in each column:")
print(df.isnull().sum())

df=df.dropna(subset=['gender'])
df['study_hours'] = df['study_hours'].fillna(df['study_hours'].mean())

print("\nAfter cleaning:")
print(df.isnull().sum())

   gender  study_hours  attendance_pct  math_score  reading_score  final_score
0    male          1.7            83.6        62.0           91.0         38.9
1     NaN          2.6            91.2        82.0           60.0         37.5
2  female          2.9            97.5        69.0           57.0         35.0
3  female          4.8            85.7        78.0           62.0         36.5
4    male          3.9           -10.0        64.0           95.0         30.9

Number of missing values in each column:
gender            8
study_hours       8
attendance_pct    0
math_score        0
reading_score     0
final_score       0
dtype: int64

After cleaning:
gender            0
study_hours       0
attendance_pct    0
math_score        0
reading_score     0
final_score       0
dtype: int64

In [30]:
#