**Steps for Modeling:**



1. Create the Model
2. Compile the Model
3. Define a loss function
4. Setting up an optimizer
5. Finding best learning size
6. Creating Evalution Metrics
7. Fitting Model
8. Improve Model

# Predict Heart Disease



1. Load Dataset
2. Split features and test
3. Train test spill
4. Scale features

In [29]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [3]:
heart_data=pd.read_csv('/content/heart.csv')
heart_data.head()

   age  sex  chol  trestbps  thalach  target
0   52    1   200       130      150       1
1   58    0   240       150      140       1
2   60    1   180       140      145       0
3   48    1   190       120      160       0
4   50    0   220       125      155       1

In [4]:
X=heart_data.drop('target',axis=1)
y=heart_data['target']
print(X)
print(y)

   age  sex  chol  trestbps  thalach
0   52    1   200       130      150
1   58    0   240       150      140
2   60    1   180       140      145
3   48    1   190       120      160
4   50    0   220       125      155
5   65    1   210       160      130
6   54    1   230       135      150
7   46    0   205       128      162
8   66    1   250       155      120
9   57    0   195       132      165
0    1
1    1
2    0
3    0
4    1
5    0
6    1
7    0
8    0
9    1
Name: target, dtype: int64

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [8]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)
#

In [13]:
model=tf.keras.Sequential(
    [tf.keras.layers.Dense(16,activation='relu',input_shape=(X_train.shape[1],)),
     tf.keras.layers.Dense(8,activation='relu'),
     tf.keras.layers.Dense(1,activation='sigmoid'),
])

In [14]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [15]:
# train the model
history_model=model.fit(X_train,y_train,epochs=100,validation_data=(X_test,y_test))

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - accuracy: 0.5000 - loss: 0.8123 - val_accuracy: 0.5000 - val_loss: 0.7604
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step - accuracy: 0.5000 - loss: 0.8055 - val_accuracy: 0.5000 - val_loss: 0.7597
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step - accuracy: 0.5000 - loss: 0.7987 - val_accuracy: 0.5000 - val_loss: 0.7591
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - accuracy: 0.5000 - loss: 0.7924 - val_accuracy: 0.5000 - val_loss: 0.7572
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step - accuracy: 0.5000 - loss: 0.7864 - val_accuracy: 0.5000 - val_loss: 0.7545
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 280ms/step - accuracy: 0.5000 - loss: 0.7805 - val_accuracy: 0.5000 - val_loss: 0.7518
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 284ms/step - accuracy: 0.5000 - loss: 0.7746 - val_accuracy: 0.5000 - val_loss: 0.7492
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 370ms/step - accuracy: 0.5000 - loss: 0.7691 - val_accuracy: 0.5000 - val_loss: 0.7467
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 481ms/step - accuracy: 0.5000 - loss: 0.7636 - val_accuracy: 0.5000 - val_loss: 0.7443
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 304ms/step - accuracy: 0.5000 - loss: 0.7583 - val_accuracy: 0.5000 - val_loss: 0.7419
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 354ms/step - accuracy: 0.5000 - loss: 0.7530 - val_accuracy: 0.5000 - val_loss: 0.7395
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 215ms/step - accuracy: 0.5000 - loss: 0.7478 - val_accuracy: 0.5000 - val_loss: 0.7371
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 275ms/step - accuracy: 0.5000 - loss: 0.7427 - val_accuracy: 0.5000 - val_loss: 0.7351
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 301ms/step - accuracy: 0.5000 - loss: 0.7376 - val_accuracy: 0.5000 - val_loss: 0.7335
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 214ms/step - accuracy: 0.5000 - loss: 0.7325 - val_accuracy: 0.5000 - val_loss: 0.7322
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - accuracy: 0.5000 - loss: 0.7275 - val_accuracy: 0.5000 - val_loss: 0.7310
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 380ms/step - accuracy: 0.5000 - loss: 0.7225 - val_accuracy: 0.5000 - val_loss: 0.7300
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 241ms/step - accuracy: 0.5000 - loss: 0.7176 - val_accuracy: 0.5000 - val_loss: 0.7289
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 178ms/step - accuracy: 0.6250 - loss: 0.7129 - val_accuracy: 0.5000 - val_loss: 0.7277
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - accuracy: 0.6250 - loss: 0.7086 - val_accuracy: 0.5000 - val_loss: 0.7263
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 299ms/step - accuracy: 0.6250 - loss: 0.7044 - val_accuracy: 0.5000 - val_loss: 0.7249
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step - accuracy: 0.6250 - loss: 0.7002 - val_accuracy: 0.5000 - val_loss: 0.7235
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 191ms/step - accuracy: 0.6250 - loss: 0.6961 - val_accuracy: 0.5000 - val_loss: 0.7220
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - accuracy: 0.6250 - loss: 0.6921 - val_accuracy: 0.5000 - val_loss: 0.7204
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 294ms/step - accuracy: 0.7500 - loss: 0.6882 - val_accuracy: 0.5000 - val_loss: 0.7191
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 328ms/step - accuracy: 0.7500 - loss: 0.6844 - val_accuracy: 0.5000 - val_loss: 0.7180
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - accuracy: 0.7500 - loss: 0.6806 - val_accuracy: 0.5000 - val_loss: 0.7171
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 296ms/step - accuracy: 0.6250 - loss: 0.6769 - val_accuracy: 0.5000 - val_loss: 0.7160
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 328ms/step - accuracy: 0.6250 - loss: 0.6732 - val_accuracy: 0.5000 - val_loss: 0.7148
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - accuracy: 0.6250 - loss: 0.6695 - val_accuracy: 0.5000 - val_loss: 0.7136
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step - accuracy: 0.6250 - loss: 0.6658 - val_accuracy: 0.5000 - val_loss: 0.7123
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 210ms/step - accuracy: 0.7500 - loss: 0.6622 - val_accuracy: 0.5000 - val_loss: 0.7110
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 264ms/step - accuracy: 0.7500 - loss: 0.6587 - val_accuracy: 0.5000 - val_loss: 0.7099
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 175ms/step - accuracy: 0.7500 - loss: 0.6551 - val_accuracy: 0.5000 - val_loss: 0.7091
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 351ms/step - accuracy: 0.7500 - loss: 0.6516 - val_accuracy: 0.5000 - val_loss: 0.7085
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 495ms/step - accuracy: 0.7500 - loss: 0.6482 - val_accuracy: 0.5000 - val_loss: 0.7077
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 318ms/step - accuracy: 0.7500 - loss: 0.6448 - val_accuracy: 0.5000 - val_loss: 0.7068
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 538ms/step - accuracy: 0.7500 - loss: 0.6413 - val_accuracy: 0.5000 - val_loss: 0.7063
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 308ms/step - accuracy: 0.7500 - loss: 0.6379 - val_accuracy: 0.5000 - val_loss: 0.7059
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 182ms/step - accuracy: 0.7500 - loss: 0.6346 - val_accuracy: 0.5000 - val_loss: 0.7054
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 318ms/step - accuracy: 0.7500 - loss: 0.6313 - val_accuracy: 0.5000 - val_loss: 0.7051
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 190ms/step - accuracy: 0.7500 - loss: 0.6280 - val_accuracy: 0.5000 - val_loss: 0.7051
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - accuracy: 0.7500 - loss: 0.6248 - val_accuracy: 0.5000 - val_loss: 0.7053
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step - accuracy: 0.7500 - loss: 0.6216 - val_accuracy: 0.5000 - val_loss: 0.7052
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - accuracy: 0.7500 - loss: 0.6185 - val_accuracy: 0.5000 - val_loss: 0.7049
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 175ms/step - accuracy: 0.7500 - loss: 0.6153 - val_accuracy: 0.5000 - val_loss: 0.7043
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 198ms/step - accuracy: 0.7500 - loss: 0.6122 - val_accuracy: 0.5000 - val_loss: 0.7039
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 178ms/step - accuracy: 0.7500 - loss: 0.6091 - val_accuracy: 0.5000 - val_loss: 0.7038
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 184ms/step - accuracy: 0.7500 - loss: 0.6060 - val_accuracy: 0.5000 - val_loss: 0.7039
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - accuracy: 0.7500 - loss: 0.6029 - val_accuracy: 0.5000 - val_loss: 0.7037
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 324ms/step - accuracy: 0.7500 - loss: 0.5998 - val_accuracy: 0.5000 - val_loss: 0.7034
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 190ms/step - accuracy: 0.7500 - loss: 0.5967 - val_accuracy: 0.5000 - val_loss: 0.7033
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 183ms/step - accuracy: 0.7500 - loss: 0.5940 - val_accuracy: 0.5000 - val_loss: 0.7033
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step - accuracy: 0.7500 - loss: 0.5912 - val_accuracy: 0.5000 - val_loss: 0.7030
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - accuracy: 0.7500 - loss: 0.5885 - val_accuracy: 0.5000 - val_loss: 0.7029
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step - accuracy: 0.7500 - loss: 0.5857 - val_accuracy: 0.5000 - val_loss: 0.7030
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 265ms/step - accuracy: 0.7500 - loss: 0.5830 - val_accuracy: 0.5000 - val_loss: 0.7033
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 260ms/step - accuracy: 0.7500 - loss: 0.5802 - val_accuracy: 0.5000 - val_loss: 0.7035
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 313ms/step - accuracy: 0.7500 - loss: 0.5774 - val_accuracy: 0.5000 - val_loss: 0.7038
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 331ms/step - accuracy: 0.7500 - loss: 0.5747 - val_accuracy: 0.5000 - val_loss: 0.7042
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 309ms/step - accuracy: 0.7500 - loss: 0.5719 - val_accuracy: 0.5000 - val_loss: 0.7046
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 522ms/step - accuracy: 0.7500 - loss: 0.5692 - val_accuracy: 0.5000 - val_loss: 0.7047
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 255ms/step - accuracy: 0.7500 - loss: 0.5664 - val_accuracy: 0.5000 - val_loss: 0.7046
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 334ms/step - accuracy: 0.8750 - loss: 0.5636 - val_accuracy: 0.5000 - val_loss: 0.7043
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 475ms/step - accuracy: 0.8750 - loss: 0.5609 - val_accuracy: 0.5000 - val_loss: 0.7041
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 285ms/step - accuracy: 0.8750 - loss: 0.5581 - val_accuracy: 0.5000 - val_loss: 0.7047
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 312ms/step - accuracy: 0.8750 - loss: 0.5554 - val_accuracy: 0.5000 - val_loss: 0.7058
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 302ms/step - accuracy: 0.8750 - loss: 0.5527 - val_accuracy: 0.5000 - val_loss: 0.7070
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 303ms/step - accuracy: 0.8750 - loss: 0.5502 - val_accuracy: 0.5000 - val_loss: 0.7081
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 259ms/step - accuracy: 0.8750 - loss: 0.5476 - val_accuracy: 0.5000 - val_loss: 0.7092
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - accuracy: 0.8750 - loss: 0.5449 - val_accuracy: 0.5000 - val_loss: 0.7102
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 329ms/step - accuracy: 0.8750 - loss: 0.5422 - val_accuracy: 0.5000 - val_loss: 0.7115
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 328ms/step - accuracy: 0.8750 - loss: 0.5396 - val_accuracy: 0.5000 - val_loss: 0.7131
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 182ms/step - accuracy: 0.8750 - loss: 0.5370 - val_accuracy: 0.5000 - val_loss: 0.7149
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 213ms/step - accuracy: 0.8750 - loss: 0.5344 - val_accuracy: 0.5000 - val_loss: 0.7168
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.8750 - loss: 0.5319 - val_accuracy: 0.5000 - val_loss: 0.7182
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.8750 - loss: 0.5293 - val_accuracy: 0.5000 - val_loss: 0.7197
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.8750 - loss: 0.5267 - val_accuracy: 0.5000 - val_loss: 0.7212
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.8750 - loss: 0.5241 - val_accuracy: 0.5000 - val_loss: 0.7226
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.8750 - loss: 0.5215 - val_accuracy: 0.5000 - val_loss: 0.7240
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.8750 - loss: 0.5189 - val_accuracy: 0.5000 - val_loss: 0.7256
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.8750 - loss: 0.5163 - val_accuracy: 0.5000 - val_loss: 0.7273
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 0.8750 - loss: 0.5137 - val_accuracy: 0.5000 - val_loss: 0.7290
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.8750 - loss: 0.5112 - val_accuracy: 0.5000 - val_loss: 0.7306
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.8750 - loss: 0.5087 - val_accuracy: 0.5000 - val_loss: 0.7324
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.8750 - loss: 0.5062 - val_accuracy: 0.5000 - val_loss: 0.7344
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.8750 - loss: 0.5037 - val_accuracy: 0.5000 - val_loss: 0.7361
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.8750 - loss: 0.5012 - val_accuracy: 0.5000 - val_loss: 0.7380
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.8750 - loss: 0.4987 - val_accuracy: 0.5000 - val_loss: 0.7399
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.8750 - loss: 0.4962 - val_accuracy: 0.5000 - val_loss: 0.7419
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.8750 - loss: 0.4937 - val_accuracy: 0.5000 - val_loss: 0.7438
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.8750 - loss: 0.4913 - val_accuracy: 0.5000 - val_loss: 0.7457
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 0.8750 - loss: 0.4888 - val_accuracy: 0.5000 - val_loss: 0.7473
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.8750 - loss: 0.4862 - val_accuracy: 0.5000 - val_loss: 0.7492
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.8750 - loss: 0.4836 - val_accuracy: 0.5000 - val_loss: 0.7514
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.8750 - loss: 0.4809 - val_accuracy: 0.5000 - val_loss: 0.7537
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.8750 - loss: 0.4783 - val_accuracy: 0.5000 - val_loss: 0.7562
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.8750 - loss: 0.4757 - val_accuracy: 0.5000 - val_loss: 0.7585
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.8750 - loss: 0.4732 - val_accuracy: 0.5000 - val_loss: 0.7608
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.8750 - loss: 0.4706 - val_accuracy: 0.5000 - val_loss: 0.7628

In [17]:
# Evalute the Model
loss,accuracy = model.evaluate(X_test, y_test)
print(f'Loss:{loss} , Accuracy:{accuracy}')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.5000 - loss: 0.7628
Loss:0.762811541557312 , Accuracy:0.5

# Example 2

*   Bank customer Exit Prediction.
*   Based on given data using Neural Network Binary Classifier find out is a customer going to stay or leave
stay: (churn=0) and leave (churn=1)

In [68]:
#Example
bank_data=pd.read_csv('/content/bank_churn.csv')
bank_data.head()

   CreditScore Geography  Gender  ...  NumOfProducts  EstimatedSalary  Exited
0          600    France    Male  ...              1            50000       0
1          700     Spain  Female  ...              2            60000       0
2          800   Germany  Female  ...              1            70000       1
3          400    France    Male  ...              1            40000       1
4          550     Spain    Male  ...              2            42000       0

[5 rows x 8 columns]

In [69]:
bank_data = pd.read_csv('/content/bank_churn.csv')

In [70]:
le = LabelEncoder()
bank_data['Gender'] = le.fit_transform(bank_data['Gender'])
bank_data = pd.get_dummies(bank_data, columns=['Geography'])

In [71]:
X = bank_data.drop('Exited', axis=1)
y = bank_data['Exited']

In [72]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=43)

In [73]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [75]:
bank_model = tf.keras.Sequential([
    tf.keras.layers.Dense(16, activation='relu', input_shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(8, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [76]:
bank_model.compile(optimizer='adam',
                   loss='binary_crossentropy',
                   metrics=['accuracy'])
bank_model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_27 (Dense)                │ (None, 16)             │           160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_28 (Dense)                │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_29 (Dense)                │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 305 (1.19 KB)

 Trainable params: 305 (1.19 KB)

 Non-trainable params: 0 (0.00 B)

In [77]:
bank_model1_history = bank_model.fit(X_train, y_train, epochs=100, validation_data=(X_test, y_test))

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.7500 - loss: 0.6584 - val_accuracy: 0.5000 - val_loss: 0.8333
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.7500 - loss: 0.6531 - val_accuracy: 0.5000 - val_loss: 0.8400
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.7500 - loss: 0.6479 - val_accuracy: 0.5000 - val_loss: 0.8467
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.7500 - loss: 0.6428 - val_accuracy: 0.5000 - val_loss: 0.8534
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.7500 - loss: 0.6377 - val_accuracy: 0.5000 - val_loss: 0.8600
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.7500 - loss: 0.6335 - val_accuracy: 0.5000 - val_loss: 0.8666
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.7500 - loss: 0.6293 - val_accuracy: 0.5000 - val_loss: 0.8732
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.7500 - loss: 0.6251 - val_accuracy: 0.5000 - val_loss: 0.8798
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.7500 - loss: 0.6209 - val_accuracy: 0.5000 - val_loss: 0.8863
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.7500 - loss: 0.6168 - val_accuracy: 0.5000 - val_loss: 0.8929
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.7500 - loss: 0.6128 - val_accuracy: 0.5000 - val_loss: 0.8996
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.7500 - loss: 0.6087 - val_accuracy: 0.5000 - val_loss: 0.9063
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.7500 - loss: 0.6045 - val_accuracy: 0.5000 - val_loss: 0.9130
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.7500 - loss: 0.6004 - val_accuracy: 0.5000 - val_loss: 0.9198
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.7500 - loss: 0.5963 - val_accuracy: 0.5000 - val_loss: 0.9265
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - accuracy: 0.7500 - loss: 0.5921 - val_accuracy: 0.5000 - val_loss: 0.9333
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.7500 - loss: 0.5881 - val_accuracy: 0.5000 - val_loss: 0.9400
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.7500 - loss: 0.5842 - val_accuracy: 0.5000 - val_loss: 0.9466
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.7500 - loss: 0.5804 - val_accuracy: 0.5000 - val_loss: 0.9532
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.7500 - loss: 0.5766 - val_accuracy: 0.5000 - val_loss: 0.9597
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.7500 - loss: 0.5736 - val_accuracy: 0.5000 - val_loss: 0.9658
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.7500 - loss: 0.5704 - val_accuracy: 0.5000 - val_loss: 0.9718
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - accuracy: 0.7500 - loss: 0.5670 - val_accuracy: 0.5000 - val_loss: 0.9770
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.7500 - loss: 0.5635 - val_accuracy: 0.5000 - val_loss: 0.9821
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.7500 - loss: 0.5600 - val_accuracy: 0.5000 - val_loss: 0.9871
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.7500 - loss: 0.5564 - val_accuracy: 0.5000 - val_loss: 0.9921
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.7500 - loss: 0.5527 - val_accuracy: 0.5000 - val_loss: 0.9971
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.7500 - loss: 0.5490 - val_accuracy: 0.5000 - val_loss: 1.0022
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.7500 - loss: 0.5453 - val_accuracy: 0.5000 - val_loss: 1.0073
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.7500 - loss: 0.5417 - val_accuracy: 0.5000 - val_loss: 1.0124
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.7500 - loss: 0.5385 - val_accuracy: 0.5000 - val_loss: 1.0178
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.7500 - loss: 0.5352 - val_accuracy: 0.5000 - val_loss: 1.0234
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.7500 - loss: 0.5319 - val_accuracy: 0.5000 - val_loss: 1.0292
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.7500 - loss: 0.5285 - val_accuracy: 0.5000 - val_loss: 1.0352
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - accuracy: 0.8750 - loss: 0.5251 - val_accuracy: 0.5000 - val_loss: 1.0413
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.8750 - loss: 0.5218 - val_accuracy: 0.5000 - val_loss: 1.0476
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.5185 - val_accuracy: 0.5000 - val_loss: 1.0539
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.5152 - val_accuracy: 0.5000 - val_loss: 1.0604
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 1.0000 - loss: 0.5118 - val_accuracy: 0.5000 - val_loss: 1.0671
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 1.0000 - loss: 0.5087 - val_accuracy: 0.5000 - val_loss: 1.0736
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.5056 - val_accuracy: 0.5000 - val_loss: 1.0801
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 1.0000 - loss: 0.5024 - val_accuracy: 0.5000 - val_loss: 1.0866
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 1.0000 - loss: 0.4991 - val_accuracy: 0.5000 - val_loss: 1.0932
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 1.0000 - loss: 0.4959 - val_accuracy: 0.5000 - val_loss: 1.0999
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - accuracy: 1.0000 - loss: 0.4927 - val_accuracy: 0.5000 - val_loss: 1.1070
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 1.0000 - loss: 0.4895 - val_accuracy: 0.5000 - val_loss: 1.1143
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 1.0000 - loss: 0.4863 - val_accuracy: 0.5000 - val_loss: 1.1219
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 180ms/step - accuracy: 1.0000 - loss: 0.4830 - val_accuracy: 0.5000 - val_loss: 1.1298
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - accuracy: 1.0000 - loss: 0.4797 - val_accuracy: 0.5000 - val_loss: 1.1379
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 289ms/step - accuracy: 1.0000 - loss: 0.4766 - val_accuracy: 0.5000 - val_loss: 1.1460
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step - accuracy: 1.0000 - loss: 0.4735 - val_accuracy: 0.5000 - val_loss: 1.1541
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 1.0000 - loss: 0.4702 - val_accuracy: 0.5000 - val_loss: 1.1621
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 1.0000 - loss: 0.4667 - val_accuracy: 0.5000 - val_loss: 1.1701
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - accuracy: 1.0000 - loss: 0.4635 - val_accuracy: 0.5000 - val_loss: 1.1780
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - accuracy: 1.0000 - loss: 0.4604 - val_accuracy: 0.5000 - val_loss: 1.1861
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 182ms/step - accuracy: 1.0000 - loss: 0.4572 - val_accuracy: 0.5000 - val_loss: 1.1944
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 275ms/step - accuracy: 1.0000 - loss: 0.4541 - val_accuracy: 0.5000 - val_loss: 1.2028
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - accuracy: 1.0000 - loss: 0.4509 - val_accuracy: 0.5000 - val_loss: 1.2115
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - accuracy: 1.0000 - loss: 0.4477 - val_accuracy: 0.5000 - val_loss: 1.2203
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.4445 - val_accuracy: 0.5000 - val_loss: 1.2291
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 1.0000 - loss: 0.4412 - val_accuracy: 0.5000 - val_loss: 1.2379
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 1.0000 - loss: 0.4382 - val_accuracy: 0.5000 - val_loss: 1.2469
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 1.0000 - loss: 0.4352 - val_accuracy: 0.5000 - val_loss: 1.2560
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 1.0000 - loss: 0.4320 - val_accuracy: 0.5000 - val_loss: 1.2652
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 1.0000 - loss: 0.4288 - val_accuracy: 0.5000 - val_loss: 1.2744
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 1.0000 - loss: 0.4257 - val_accuracy: 0.5000 - val_loss: 1.2839
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 1.0000 - loss: 0.4226 - val_accuracy: 0.5000 - val_loss: 1.2933
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.4195 - val_accuracy: 0.5000 - val_loss: 1.3027
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.4163 - val_accuracy: 0.5000 - val_loss: 1.3125
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.4130 - val_accuracy: 0.5000 - val_loss: 1.3225
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.4099 - val_accuracy: 0.5000 - val_loss: 1.3325
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - accuracy: 1.0000 - loss: 0.4068 - val_accuracy: 0.5000 - val_loss: 1.3425
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 1.0000 - loss: 0.4035 - val_accuracy: 0.5000 - val_loss: 1.3524
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 1.0000 - loss: 0.4003 - val_accuracy: 0.5000 - val_loss: 1.3626
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.3972 - val_accuracy: 0.5000 - val_loss: 1.3730
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 1.0000 - loss: 0.3940 - val_accuracy: 0.5000 - val_loss: 1.3838
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 1.0000 - loss: 0.3909 - val_accuracy: 0.5000 - val_loss: 1.3946
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 1.0000 - loss: 0.3878 - val_accuracy: 0.5000 - val_loss: 1.4053
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.3847 - val_accuracy: 0.5000 - val_loss: 1.4162
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 1.0000 - loss: 0.3815 - val_accuracy: 0.5000 - val_loss: 1.4272
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 1.0000 - loss: 0.3783 - val_accuracy: 0.5000 - val_loss: 1.4384
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - accuracy: 1.0000 - loss: 0.3751 - val_accuracy: 0.5000 - val_loss: 1.4500
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.3720 - val_accuracy: 0.5000 - val_loss: 1.4617
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 1.0000 - loss: 0.3689 - val_accuracy: 0.5000 - val_loss: 1.4735
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 1.0000 - loss: 0.3657 - val_accuracy: 0.5000 - val_loss: 1.4853
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 1.0000 - loss: 0.3626 - val_accuracy: 0.5000 - val_loss: 1.4972
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 1.0000 - loss: 0.3595 - val_accuracy: 0.5000 - val_loss: 1.5092
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 1.0000 - loss: 0.3564 - val_accuracy: 0.5000 - val_loss: 1.5215
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 1.0000 - loss: 0.3533 - val_accuracy: 0.5000 - val_loss: 1.5339
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 1.0000 - loss: 0.3502 - val_accuracy: 0.5000 - val_loss: 1.5463
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 1.0000 - loss: 0.3471 - val_accuracy: 0.5000 - val_loss: 1.5589
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 1.0000 - loss: 0.3441 - val_accuracy: 0.5000 - val_loss: 1.5715
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 1.0000 - loss: 0.3411 - val_accuracy: 0.5000 - val_loss: 1.5844
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 1.0000 - loss: 0.3381 - val_accuracy: 0.5000 - val_loss: 1.5976
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 1.0000 - loss: 0.3351 - val_accuracy: 0.5000 - val_loss: 1.6108
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - accuracy: 1.0000 - loss: 0.3320 - val_accuracy: 0.5000 - val_loss: 1.6245
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.3290 - val_accuracy: 0.5000 - val_loss: 1.6381
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 1.0000 - loss: 0.3260 - val_accuracy: 0.5000 - val_loss: 1.6518
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 1.0000 - loss: 0.3231 - val_accuracy: 0.5000 - val_loss: 1.6655
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 1.0000 - loss: 0.3201 - val_accuracy: 0.5000 - val_loss: 1.6795

In [83]:
# Evaluate
loss, accuracy = bank_model.evaluate(X_test, y_test)
print(f'Test Loss: {loss:.4f}')
print(f'Test Accuracy: {accuracy:.4f}')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 1.6795
Test Loss: 1.6795
Test Accuracy: 0.5000

In [97]:
# predict a new customer

new_customer=pd.DataFrame({
    'CreditScore':[720],
    'Geography': 'France',
    'Gender': 'Male',
    'Age':[42],
    'Balance':[62000],
    'NumOfProducts':[1],
    'EstimatedSalary':[55000]
})

new_customer['Gender']=le.transform(new_customer['Gender'])
new_customer=pd.get_dummies(new_customer,columns=['Geography'],drop_first=True)

for col in [c for c in X.columns if c not in new_customer.columns]:
    new_customer[col]=0

new_customer=new_customer[X.columns]
new_scaled=scaler.transform(new_customer)

pred=bank_model.predict(new_scaled)
if pred[0][0] > 0.5:
  print('Customer will leave')
  print(pred[0][0])
else:
  print('Customer will not leave')
  print(pred[0][0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
Customer will not leave
0.31319577