# SUPERVISED MACHINE LEARNING
 ## LINEAR REGRESSION

In [4]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import numpy as np

In [5]:
data=pd.read_csv('sales_data.csv')
data.head()

   Advertising_Spend  Sales_Revenue
0               1000          12000
1               1500          15000
2               2000          18000
3               2500          20000
4               3000          23000

In [6]:
x=data[['Advertising_Spend']]
y=data['Sales_Revenue']

In [19]:
model= LinearRegression()
model.fit(x,y)

LinearRegression()

In [21]:
new_spend= float(input('Enter New Spend to Predict Sales Revenue'))
predicted_revenue= model.predict([new_spend])
print(f'New spend {new_spend} Predicted Revenue {predicted_revenue}')

Enter New Spend to Predict Sales Revenue 4

C:\Users\User\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

ValueError: Expected 2D array, got 1D array instead:
array=[4.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [22]:
# import the required libraries
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [39]:
# collecting data
df=pd.read_csv('sales_data.csv')

In [24]:
df.head(2)

   Advertising_Spend  Sales_Revenue
0               1000          12000
1               1500          15000

In [28]:
adv_spend=df[['Advertising_Spend']]
sales_rev=df['Sales_Revenue']
print(adv_spend)
print(sales_rev)

   Advertising_Spend
0               1000
1               1500
2               2000
3               2500
4               3000
5               3500
6               4000
0    12000
1    15000
2    18000
3    20000
4    23000
5    25000
6    28000
Name: Sales_Revenue, dtype: int64

In [37]:
# model creation
model=LinearRegression()

In [38]:
# trained the model
model.fit(adv_spend,sales_rev)

LinearRegression()

In [40]:
# prediction
pr_value=model.predict([[2700]])
print(pr_value)

[21185.71428571]

C:\Users\User\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [41]:
#

# 1. Linear regression - house of price
## download house_price.csv file from github
## **Goal:** Train a Linear Rgeression model to predict hosue price from Size_sqft.

In [42]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [46]:
df=pd.read_csv('house_price.csv')
df.head()

   Size_sqft   Price
0       1000  150000
1       1200  170000
2       1500  200000
3       1800  230000
4       2000  260000

In [58]:
df = df.replace('?', np.nan)
df = df.dropna()
df['Size_sqft'] = df['Size_sqft'].astype(float)
df['Price'] = df['Price'].astype(float)

In [59]:
X = df[['Size_sqft']]
y = df['Price']

In [64]:
model = LinearRegression()
model.fit(X, y)
print("Training done successfully!")

Training done successfully!

In [65]:
print("Coefficient (Slope):", model.coef_[0])
print("Intercept:", model.intercept_)

Coefficient (Slope): 107.3529411764706
Intercept: 40970.5882352941

In [67]:
new_size = float(input("Enter house size (sqft) to predict price: "))
new_data = pd.DataFrame({'Size_sqft': [new_size]}) 
predicted_price = model.predict(new_data)
print(f"Predicted price for {new_size} sqft house is: ${predicted_price[0]:.2f}")

Enter house size (sqft) to predict price:  2002

Predicted price for 2002.0 sqft house is: $255891.18