# 2. Logistic Regression - Pass/Fail

In [12]:
# imported all required libraries
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression

In [14]:
# collect data
df=pd.read_csv('pass_fail.csv')
df.head()

   Hours Result
0      1   Fail
1      2   Fail
2      3   Fail
3      4   Pass
4      5   Pass

In [15]:
# split the data
X= df[['Hours']]
y= df['Result']

In [16]:
# create the model(change here only, we are using Logistic Regression)
model=LogisticRegression()

In [17]:
# trained the model
model.fit(X,y)

LogisticRegression()

In [27]:
pred_35= model.predict([[3.5]])
print('Predicted result for 3.5 hours:', pred_35[0])

Predicted result for 3.5 hours: Pass

C:\Users\User\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [28]:
hours_study=int(input('Number of hours studied'))
pred_value=model.predict([[hours_study]])
print(f'After {hours_study} you are likely to {pred_value[0]}')

Number of hours studied 5

After 5 you are likely to Pass

C:\Users\User\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [29]:
#

In [30]:
# imported all required libraries
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder

In [32]:
df=pd.read_csv('customer_purchase.csv')
df.head()

   Age  Salary Purchased
0   22   25000        No
1   25   30000        No
2   30   40000       Yes
3   35   50000       Yes
4   40   60000       Yes

In [38]:
# data split and labelling
le= LabelEncoder()
df['Purchased'] = le.fit_transform(df['Purchased'])
X = df[['Age', 'Salary']]
y= df['Purchased']

In [37]:
df

   Age  Salary  Purchased
0   22   25000          0
1   25   30000          0
2   30   40000          1
3   35   50000          1
4   40   60000          1

In [46]:
# creating the model
model=LogisticRegression()

In [47]:
# training the  model
model.fit(X,y)

LogisticRegression()

In [55]:
# Prediction
# assign fix value
new_cust = [[28,35000]]
prediction = model.predict(new_cust)
print(f'Predicted result (1=Yes, 0=No): {prediction[0]}')

Predicted result (1=Yes, 0=No): 1

C:\Users\User\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [57]:
# Prediction: Predict the result
new_cust_age = int(input('Enter Age'))
new_cust_sal = int(input('Enter Salary'))
new_cust = [[new_cust_age,new_cust_sal]]
new_cust = model.predict(new_cust)
if (prediction):
    print('Likely Purchased')
else:
    print('Likely Not Purchased')

Enter Age 67
Enter Salary 76767

Likely Purchased

C:\Users\User\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [58]:
#

# Logistc Regression - Spam/NotSpam
## Download spam_data.csv from https://www.kaggle.com/
## Load the data
## Do the data cleaning and labeling (if required)
## Use Logistic Regression Algorithm to trained the model
## Predict result if the email is spam or not spam

In [71]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import LabelEncoder

In [99]:
df=pd.read_csv('spam_dataset.csv')
df

                                       message_content  is_spam
0    Hello Lonnie,\n\nJust wanted to touch base reg...        0
1    Congratulations, you've won a prize! Call us n...        1
2    You have been pre-approved for a credit card w...        1
3    Limited time offer, act now! Only a few spots ...        1
4    Your loan has been approved! Transfer funds to...        1
..                                                 ...      ...
995  Hello Virginia,\n\nIt was great to catch up wi...        0
996  Final notice: Claim your inheritance from a di...        1
997  Hot singles in your area want to chat! Contact...        1
998  Your loan has been approved! Transfer funds to...        1
999  Dear Brian,\n\nI wanted to let you know about ...        0

[1000 rows x 2 columns]

In [120]:
X = df['message_content']
y = df['is_spam']

In [121]:
cv = CountVectorizer()
X_cv = cv.fit_transform(X)

In [122]:
model = LogisticRegression()

In [123]:
model.fit(X_cv,y)

LogisticRegression()

In [128]:
sample = ['Hi Joe']
pred = model.predict(cv.transform(sample))
if(pred.any()):
    print('Not Spam')
else:
    print('SPAM')

Not Spam

In [130]:
xSpam = df['message_content']
ySpam = df['is_spam']
 
# Split the data (e.g., 80% for training, 20% for testing)
X_train_text, X_test_text, y_train, y_test = train_test_split(
    xSpam, 
    ySpam, 
    test_size=0.2, 
    random_state=42
)
print("Training samples:", len(X_train_text))
print("Testing samples:", len(X_test_text))
 
vectorizer = CountVectorizer()
X_train_numeric = vectorizer.fit_transform(X_train_text)
X_test_numeric = vectorizer.transform(X_test_text)
 
model_spam_email = LogisticRegression() 
model_spam_email.fit(X_train_numeric, y_train)

Training samples: 808
Testing samples: 202

LogisticRegression()

In [134]:
sample = input('Enter the message')
pred = model.predict(cv.transform([sample]))
if(pred.any(0)):
    print('Not Spam')
else:
    print('SPAM')

Enter the message tyu

Not Spam